### PR TITLE
Add no_std support

### PR DESCRIPTION
**Pull request by whitequark**
Can I get an 1.1.0 release after that, pretty please?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-quicksort/2)

### CODE REVIEW

**Comment by whitequark** [comment]
cc @SimonSapin I think?

**Comment by whitequark** [comment]
@Manishearth wow that was fast, thanks

**Comment by notriddle** [comment]
@whitequark: Servo's not using this any more, because it goes quadratic when the list is already sorted. Maybe you want [quickersort](https://github.com/notriddle/quickersort) instead?

**Comment by whitequark** [comment]
@notriddle 
1. I need to sort eight elements or so, and I never sort fully sorted lists.
2. I don't like the amount of unnecessary dependencies quickersort has (unreachable, nodrop), as well as the fact that I will also have to port it to no_std, which is complicated by the fact that it depends on num_traits.

**Comment by notriddle** [comment]
1. Maybe just use an insertion sort? quickersort's cutoff for switching from partition sort to insertion sort is 10 elements, and that's unusually low.
2. For the record, the `num_traits` dependency is optional, and I just added `#[no_std]` support (just don't turn float support on). Though, again, if you're only doing single-digit elements, you probably just want to use insertion sort; quicksort won't perform that well, and quickersort is massively overkill.

**Comment by whitequark** [comment]
> Maybe just use an insertion sort?

Thanks for the suggestion, I will do that.

**Pull request merged**
