### PR TITLE
Bump to 1.1.0

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-quicksort/3)

### CODE REVIEW

**Comment by KiChjang** [comment]
Fix commit message plz

**Comment by Manishearth** [comment]
fixed

**Comment by KiChjang** [comment]
Still says 1.10 instead of 1.1.0 on the commit message.

**Comment by Manishearth** [comment]
now fixed

-Manish Goregaokar

**Pull request merged**
